# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSMLKitNLP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/MLNaturalLanguage'
pod 'Firebase/MLNLLanguageID'
pod 'Firebase/MLNLTranslate'
pod 'Firebase/MLCommon'
pod 'Firebase/MLNLSmartReply'
  # Pods for iOSMLKitNLP

end
